### PR TITLE
Style black

### PR DESCRIPTION
**Pull request by HeyMerlin**
This is the start of applying the following: 
- Google Style Guide https://google.github.io/styleguide/pyguide.html
- Pep 8 Style Guide https://peps.python.org/pep-0008/
Specifically this PR has no code changes and consists of changes in formatting as well as adding docstring information to many of the functions. This is more to go but this is a start.

### CODE REVIEW

**Comment by Frigyes06** [comment]
Based PR. Will review in a bit.
But also FYI: There are tools to automate PEP8

**Review by Frigyes06 — COMMENTED** [review]
Liberal application of frozenset. Is it needed? It worked last time I touched it

GH action file, could just modify existing one

Most linting I see is capitalization in comments lol. interesting why tests fail. I recommend enabling runs on each push so we can work out it's quirks quicker

**Comment by makeasnek** [comment]
@Frigyes06 maybe that's just the way the diff is making it look? If I go to "files changed" and look at, for example, README.md I see the section "FTM keeps requesting tasks from or crunching a project..." as being added, yet it's clearly in the existing readme.md.

**Comment by makeasnek** [comment]
I'll take a final read through and get this merged tomorrow if everything looks good, I think I have a better understanding now of how to read the diffs, apologies for the delay on my end :).

**Review by makeasnek — APPROVED** [review]
Thank you for your help, this looks great! Merging.

**Comment by Frigyes06** [comment]
> @Frigyes06 maybe that's just the way the diff is making it look? If I go to "files changed" and look at, for example, README.md I see the section "FTM keeps requesting tasks from or crunching a project..." as being added, yet it's clearly in the existing readme.md.

Ohh, might be. GH diff viewer gets a bit funky sometimes :)

**Pull request merged**
